// export const USER_MANAGEMENT = 'USER_MANAGEMENT';
// export const CONTRACT_MANAGEMENT = 'CONTRACT_MANAGEMENT';

export default {
    CONTRACT_MANAGEMENT: 'CONTRACT_MANAGEMENT',
    USER_MANAGEMENT: 'USER_MANAGEMENT',
}